# Home Gmail Configuration for Sieve
account:
  name: "home"
  email: "scott.a.idler@gmail.com"
  script-id: "1lf8UMzZd20KZRZpe9VzMkkMa8ZWdbIMSKdaosqEin8YawiqxR6lkjfqN"

# Message filtering rules
message-filters:
  # High-priority home emails
  - name: "family-urgent"
    to: ['scott.a.idler@gmail.com']
    cc: []
    from: ['*@family-domain.com', 'important-person@gmail.com']
    labels: ['INBOX']
    actions:
      - type: "star"
      - type: "flag"
        label: "Important"

  # Newsletter management
  - name: "newsletters"
    from: ['*@newsletter.com', '*@substack.com']
    labels: ['INBOX']
    actions:
      - type: "move"
        destination: "Newsletters"

# State-based filtering (age-off rules)
state-filters:
  # Protected messages
  - name: "starred-protection"
    labels: ['Important', 'Starred']
    ttl: "keep"

  # Standard inbox cleanup
  - name: "inbox-cleanup"
    labels: ['INBOX']
    exclude-labels: ['Important', 'Starred']
    ttl:
      read: "7d"
      unread: "21d"
    actions:
      - type: "move"
        destination: "Archive"

  # Newsletter cleanup
  - name: "newsletter-cleanup"
    labels: ['Newsletters']
    ttl:
      read: "3d"
      unread: "21d"
    actions:
      - type: "delete"

# Threading configuration
threading:
  enabled: true
  # Only age-off threads when ALL messages meet criteria
  require-all-messages-aged: true
  # Preserve threads with recent activity
  recent-activity-threshold: "24h"# Trigger workflow
# Updated clasp permissions
# Test raw JSON clasp tokens
